version: '3.8'

services:
  sftp:
    image: ghcr.io/hueske-digital/sftp:latest
    restart: unless-stopped
    volumes:
      - sftp_keys:/etc/ssh
    ports:
      - "2223:22"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536