name: Build and Push Base Docker image

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone the sftp repository
        run: git clone https://github.com/atmoz/sftp.git

      - name: Apply sshd_config.patch
        run: |
          git apply sshd_config.patch --directory=sftp

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./sftp/Dockerfile
          context: ./sftp
          tags: ghcr.io/hueske-digital/sftp:latest
          platforms: linux/amd64,linux/arm64

      - name: Do not automatically disable workflow execution
        uses: gautamkrishnar/keepalive-workflow@v1